steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-einfo-dns17:${_COMMIT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-test-123:${_COMMIT_SHA}']
    timeout: 2400s  

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'devops-einfo-dns17', '--image', 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-einfo-dns17:${_COMMIT_SHA}', '--region', 'us-east1']
images:
  - 'us-east1-docker.pkg.dev/einfo2024/services/devops-image-einfo-dns17'